### PR TITLE
Add support for preserving parts of custom error messages

### PR DESCRIPTION
**Pull request by dflemstr**
This essentially addresses a TODO from the code

### CODE REVIEW

**Comment by japaric** [comment]
Thanks for the PR. I would prefer to put this behind a Cargo feature; otherwise the size of a `Result` would increase by 2 words or more (due to alignment) for everyone, including people that use this in environments where the message can't be printed (e.g. embedded systems) but still call `unwrap` on these results.

**Comment by dflemstr** [comment]
@japaric done :)

**Comment by japaric** [comment]
Thank you!

bors r+

**Pull request merged**
